import phonenumbers
from phonenumbers import parse
from phonenumbers import geocoder
from phonenumbers import carrier
from phonenumbers import timezone
from time import sleep
import os

print("Starting Services...")
os.system("cls" if os.name == 'nt' else "clear")
sleep(0.2)

# ... (The ASCII art and other introductory prints)
sleep(1)
print('=============================================================================================================')
sleep(0.2)
print("_____________¶¶_¶¶¶¶")
sleep(0.2)
print("____________¶¶____¶¶¶")
sleep(0.2)
print("___________¶¶¶______¶¶")
sleep(0.2)
print("___________¶¶¶_______¶¶")
sleep(0.2)
print("__________¶¶¶¶________¶¶")
sleep(0.2)
print("__________¶_¶¶_________¶¶")
sleep(0.2)
print("__________¶__¶¶_________¶¶____¶¶")
sleep(0.2)
print("__________¶__¶¶__________¶¶¶¶¶¶¶")
sleep(0.2)
print("_________¶¶__¶¶¶______¶¶¶¶¶¶___¶")
sleep(0.2)
print("_________¶¶___¶¶__¶¶¶¶¶¶__¶¶")
sleep(0.2)
print("_______¶¶_¶____¶¶¶¶________¶¶")
sleep(0.2)
print("______¶¶__¶¶___¶¶__________¶¶")
sleep(0.2)
print("_____¶¶____¶¶___¶¶__________¶¶")
sleep(0.2)
print("___¶¶_______¶¶___¶¶_________¶¶")
sleep(0.2)
print("___¶¶¶¶¶¶¶¶¶¶¶¶¶__¶¶_________¶")
sleep(0.2)
print("_¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶_¶¶________¶¶")
sleep(0.2)
print("¶¶__¶¶¶¶¶¶____¶¶¶¶¶¶¶¶¶______¶¶")
sleep(0.2)
print("______¶¶¶¶¶¶¶¶¶¶¶________¶¶¶¶")
sleep(0.2)
print("_____¶¶_____¶¶___¶")
sleep(0.2)
print("_____¶______¶¶___¶")
sleep(0.2)
print("____¶¶______¶¶___¶¶")
sleep(0.2)
print("____¶¶______¶¶___¶¶")
sleep(0.2)
print("___¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶")
sleep(0.2)
print("__¶¶¶¶¶¶¶¶¶_¶¶¶¶¶¶¶¶")
sleep(0.2)
print("__¶¶________¶¶¶____¶¶")
sleep(0.2)
print("____¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶")
sleep(0.2)
print('=============================================================================================================')
sleep(2)
print("Tool made by OfficalWXP - on telegram / Skali1144 - on github.")
sleep(2)
print("[[WARNING]]: If it shows Unknown it means the Phone Number you Entered is wrong or Invalid.")
sleep(3)
print("This Won't Take Long Just Wait 5 seconds...")
sleep(7)
print("This tool works offline and online.")
sleep(4)
print("Works International - All Countries")
sleep(2)
print("==============================================================================================================")

# Parse the phone number
ph = phonenumbers.parse(input("Phone Number with + and without spaces: "))
hostname = phonenumbers.format_number(ph, phonenumbers.PhoneNumberFormat.INTERNATIONAL)
print("====================================================")
print("========>>>>>>>>> [+[ STATICS ]+] <<<<<<<<<=========")
print("====================================================")

g = geocoder.description_for_number(ph, "en")
sleep(2)
t = timezone.time_zones_for_number(ph)
print("Target: ", hostname)
sleep(2)
print("====================================================")
print("Checking possibility of Number: ", phonenumbers.is_possible_number(ph))
print("====================================================")
sleep(2)
print("Valid or Invalid Phone Number: ", phonenumbers.is_valid_number(ph))
print("====================================================")
sleep(2)
# Get the carrier name of the phone number
carrier_name = carrier.name_for_number(ph, "en")
if carrier_name:
    print("Service Provider: ", carrier_name)
else:
    print("Service Provider: Not available")
    print("================================================")
sleep(3)

# Print the country name only once
city = geocoder.description_for_number(ph, "en")
if city:
    print("Country: ", city)
else:
    print("Country: Not available")
print("====================================================")
print("TimeZone: ", timezone.time_zones_for_number(ph))
sleep(2)
print("====================================================")
sleep(2)
print("====================================================")
print("The Automation has been successfully finished.")
print("====================================================")
